name: anyscale-academy
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.8.10
  - pip
  - gym >= 0.17.2
  - numpy >= 1.18.5
  - pandas
  - requests
  - pytorch
  - torchvision
  - tqdm >= 4.37.0
  - keras
  - scikit-learn
  - holoviews >= 1.14
  - bokeh
  - ipywidgets
  - psutil
  - beautifulsoup4
  - lxml
  - dm-tree
  - scikit-image
  - lz4
  - pytz
  - nodejs
  - pip:
    - ray[default, tune]
    - xgboost
    - xgboost-ray
    - tune-sklearn
    - tensorboard >= 2.3
    - tensorflow >= 2.3
    - atoma
    - box2d-py
    - jupyter
    - jupyterlab
